### ISSUE TITLE
2 Quick issues

### ISSUE THREAD

**Issue by dreamerdad** [kissmetrics/km-support#100]
1. You may want to update this to reflect new Google Tag Manager user interface.
2. Can you clarify whether the KissMetrics tag needs to be added above the Google Analytics tag? I believe there are instructions to this effect when you sign up for a Kiss Metrics trial. If so, how does one accomplish this if one is using Google Tag Manager?

**Comment by eskfung** [comment]
@dreamerdad Google Tag Manager doesn't guarantee what order to load separate scripts. This behavior is fine in relation to loading the KISSmetrics JavaScript library. We may mention placing it above Google Analytics because that tag is easy to locate in a template, making it easier for you to put our script in an appropriate place. So essentially, don't worry about loading the two tags in the right order.

We'll look into updating the screenshots soon. Thanks for the heads up!

**Comment by dreamerdad** [comment]
Sounds good. Thanks!

**Comment by eskfung** [comment]
@dreamerdad I went back into Google Tag Manager recently and realized the screenshots are from their current interface. Which images appear out of date to you?
