### ISSUE TITLE
You can include up to 10 property columns?

### ISSUE THREAD

**Issue by oytuneren** [kissmetrics/km-support#62]
Hello,

I'm trying to upload survey results to kissmetrics with csv way however it's written "You can include up to 10 property columns."

As you can understand that surveys generally more than 10 questions and answers. We thought to add survey questions with "prob:"

Do we can do that?

**Comment by eskfung** [comment]
Hello! Sorry for taking a long time to respond. I hadn't seen a hard 10-property limit in our code, and wasn't sure if there was an actual limit. However, our CSV parser starts to encounter errors as you add more columns, especially when parsing large files.

The bottom line is, you can attempt to upload more than 10 questions/answers and see if our uploader can handle it. Otherwise, breaking one large file into separate files is the way to go.
